### ISSUE TITLE
I may have found a fix for people that it doesnt work

### ISSUE THREAD

**Issue by EnergitCZ** [MCPI-Revival/MCPIL-Legacy#11]
Hi,

i was messing around with some stuff,
and then i copied all the files from `/opt/minecraft-pi/lib/mesa`
to `/opt/minecraft-pi`, and started the newest MCPIL version.
And now all versions work!

Energit.

**Comment by NikZapp** [comment]
Thank you so much!

**Comment by EnergitCZ** [comment]
No problem.

**Comment by Alvarito050506** [comment]
Hello! And thank you for the fix!

I'm really dumb... I think that, for some reason, some RPis don't "like" the RPi-specific libraries, and the `LD_LIBRARY_PATH` ordering set by MCPIL is wrong.

Again, thanks for your contribution! I will try to integrate it into the master branch.

**Comment by OCSYT** [comment]
it still dont work ahhh

**Comment by Alvarito050506** [comment]
@OCSYT @NikZapp Does it work?

**Comment by mobilegmYT** [comment]
Fixed in [MCPIL](https://github.com/MCPI-Revival/MCPIL).
